### PR TITLE
Properly guard ptx includes for when we are in cuda mode

### LINKED ISSUE #5747: [BUG]: CUDA 13, nvcc compilation error when including `<thrust/execution_policy.h>` with THRUST_DEVICE_SYSTEM_OMP in cpp file
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

The following fails to compile with CUDA 13.0 nvcc in a .cpp file

```
//nvcc -c file.cpp -o file.o
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_OMP
#include <thrust/execution_policy.h>
```

```
In file included from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__ptx/instructions/bfind.h:26,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__bit/integral.h:24,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__cmath/ilog.h:24,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/cmath:25,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/detail/alignment.h:32,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/detail/allocator_aware_execution_policy.h:28,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/detail/seq.h:28,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/execution_policy.h:34,
                 from file.cpp:3:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__ptx/ptx_helper_functions.h: In function ‘uint32_t cuda::ptx::__4::__as_ptr_smem(const void*)’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__ptx/ptx_helper_functions.h:42:44: error: ‘__cvta_generic_to_shared’ was not declared in this scope
   42 |   return static_cast<_CUDA_VSTD::uint32_t>(__cvta_generic_to_shared(__ptr));

```

### How to Reproduce

```
//nvcc -c file.cpp -o file.o
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_OMP
#include <thrust/execution_policy.h>
```

### Expected behavior

Compiles without error.

### Reproduction link

_No response_

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by miscco**
I have expanded our host-only header tests to also include those headers from `cuda/` that we expect to also work with a host compiler

Fixes #5747

### CODE REVIEW

File: libcudacxx/include/cuda/__warp/warp_shuffle.h [hunk 1]
```diff
@@ -21,22 +21,23 @@
...
-#include <cuda/std/__type_traits/is_pointer.h>
-#include <cuda/std/__type_traits/is_void.h>
-#include <cuda/std/__type_traits/remove_cvref.h>
-#include <cuda/std/cstdint>
-
-#if __cccl_ptx_isa >= 600
-
-#  include <cuda/std/__cccl/prologue.h>
+#if _CCCL_CUDA_COMPILATION()
+#  if __cccl_ptx_isa >= 600
```
Comment (miscco) [inline libcudacxx/include/cuda/__warp/warp_shuffle.h:25]: This is kind of duplicated, because `__cccl_ptx_isa` is undefined without cuda compilation  mode, but that is some implicit knowledge that I would not want to expect, so lets always guard with `#if _CCCL_CUDA_COMPILATION()`

**Review by davebayer — APPROVED** [review]

**Review by alliepiper — APPROVED** [review]

File: libcudacxx/include/cuda/__warp/warp_shuffle.h (hunk 1 above)
Comment (fbusato) [reply libcudacxx/include/cuda/__warp/warp_shuffle.h:25]: nit. we can fuse the two condition on a single line

**Review by fbusato — APPROVED** [review]

**Comment by miscco** [comment]
I would not want to fuse them because I want the two things separate This is cuda compilation this is architecture
