### ISSUE TITLE
[BUG]: `cuda::discard_memory` fails to compile under pre-CTK 11.4

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#1082]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

When trying to compile `cuda::discard_memory` under pre-CTK 11.4, I'm getting the following compilation error:
```
ptxas /tmp/tmpxft_00013a26_00000000-6_catch2_test_vsmem.compute_80.ptx, line 17102; error   : Not a name of any known instruction: 'discard'
ptxas fatal   : Ptx assembly aborted due to errors
```

The `discard` instruction was introduced only [with PTX 7.4](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-discard).

### How to Reproduce

Call `cuda::discard_memory(...)` and compile with any CTK 11.3 or earlier. 

### Expected behavior

The program compiles fine and the PTX instruction to `discard` is only generated when supported.

### NVCC version

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
