### PR TITLE
Fix version guard for cudaDevAttrHostNumaMemoryPoolsSupported

### PR DESCRIPTION
**Pull request by hyiip**
`cudaDevAttrHostNumaMemoryPoolsSupported` was introduced in CUDA 12.9, not 12.6. The incorrect `_CCCL_CTK_AT_LEAST(12, 6)` guard causes compilation failures on CUDA 12.6-12.8 where the enum does not exist in `driver_types.h`.

Fixes build error:
`error C2039: 'cudaDevAttrHostNumaMemoryPoolsSupported': is not a member of 'global namespace'`

Introduced in #7339 (983b0c61b).

### CODE REVIEW

**Comment by leofang** [comment]
/ok to test [77e15e9](https://github.com/NVIDIA/cccl/pull/7838/commits/77e15e9262711d4b575b850f34af8a7979cb34c5)

**Comment by miscco** [comment]
Verified that this is in the 12.9 [CTK documentation](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html) but *not* in 12.8 [one ](https://docs.nvidia.com/cuda/archive/12.8.1/search.html?page=1&q=cudaDevAttrHostNumaMemoryPoolsSupported&sort=relevance)

**Review by miscco — APPROVED** [review]
