### ISSUE TITLE
[BUG]: CuPy cannot be built with CCCL v2.3.1 

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cccl#1493]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

Build time failure:
```
    Error limit reached.
    100 errors detected in the compilation of "cupy/cuda/cupy_thrust.cu".
    Compilation terminated.
    /home/leof/dev/cupy_cuda122/cupy/_core/include/cupy/_cccl/thrust/thrust/detail/type_traits.h(553): error: "thrust::detail" is ambiguous
          : thrust::detail::eval_if<
```
This happens between v2.2.0 and v2.3.1. From `git bisect`, it seems the offending commit is e21f700c44d6d4c8af8f7f6b38d5b2f650f25764
```
$ git bisect bad
e21f700c44d6d4c8af8f7f6b38d5b2f650f25764 is the first bad commit
commit e21f700c44d6d4c8af8f7f6b38d5b2f650f25764
Author: Georgy Evtushenko <evtushenko.georgy@gmail.com>
Date:   Mon Sep 11 22:10:56 2023 +0000

    Use inline arch namespace in Thrust

 thrust/thrust/detail/config/namespace.h            | 87 +++++++++++++++++++++-
 .../system/cuda/detail/core/agent_launcher.h       |  6 +-
 2 files changed, 88 insertions(+), 5 deletions(-)
```

cc: @gevtushenko for vis

### How to Reproduce

Build CuPy from source, with the CCCL submodule changed to v2.3.1
1. `git clone --recursive https://github.com/cupy/cupy.git`
2. `cd cupy; git submodule update --init --recursive`
3. `cd third_party/cccl`
4. `git fetch --tags origin`
5. `git checkout v2.3.1`
6. `cd ../..`
7. `pip install -v -e .`

### Expected behavior

Build success

### NVCC version

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```

**Comment by leofang** [comment]
From the build log, I think this was the full command invoked:
```
    Command: ['/usr/local/cuda-12.2.2/bin/nvcc', '-D_FORCE_INLINES=1', '-DCUPY_CACHE_KEY=ab177d42e646c2aa932d5d5fac58c69106a9cac1', '-DCUPY_CUB_VERSION_CODE=200200', '-DCUPY_JITIFY_VERSION_CODE=1774a3ba5', '-I/home/leof/dev/cupy_cuda122/cupy/_core/include/cupy/_cccl/libcudacxx', '-I/home/leof/dev/cupy_cuda122/cupy/_core/include/cupy/_cccl/thrust', '-I/home/leof/dev/cupy_cuda122/cupy/_core/include/cupy/_cccl/cub', '-I/home/leof/dev/cupy_cuda122/cupy/_core/include', '-I/usr/local/cuda-12.2.2/include', '-c', 'cupy/cuda/cupy_thrust.cu', '-o', 'build/temp.device_objects/cupy/cuda/cupy_thrust.cu.o', '--generate-code=arch=compute_86,code=sm_86', '--generate-code=arch=compute_89,code=sm_89', '-Xfatbin=-compress-all', '-O2', '--compiler-options="-fPIC"', '--std=c++14', '-t2', '-Xcompiler=-fno-gnu-unique']
```

**Comment by miscco** [comment]
This looks like there is an additional namespace thrust::detail defined somewhere. Could that be in your project?

**Comment by miscco** [comment]
Oh the commit is definitely causing the issue.

The issue is that nvcc has certain issues with nested namespaces. 

For nvcc there is difference between `inline namespace meow { namespace thrust { namespace detail` and `namespace thrust { namespace detail`

The commit introduced a versioning namespace that ensures that we do not accidentally mix kernels from different cccl versions.

**Comment by miscco** [comment]
Now that I think about it my guess is that you have conflicting versions of thrust in your build. One will have the inline namespace one not. 

That would create exactly that kind of issue

**Comment by miscco** [comment]
So I tried and build according to your reproducer and it does indeed fail.

I den tried to replace the offending `thrust::detail` qualifier with `THRUST_NS_QUALIFIER::detail` which should include the inline namespace identifier.

However, when actually building cupy it then expanded to plain `::thrust::detail`

That suggests that there are different versions of thrust at play

**Comment by leofang** [comment]
I might have some clue about this. CuPy censored very old thrust::complex headers which do come with a detail namespace. Getting rid of it is a long-term goal, in the meanwhile any suggestion for me to quickly work around?

**Comment by miscco** [comment]
@leofang I have opened https://github.com/cupy/cupy/pull/8221

I believe that should address your issue
