### ISSUE TITLE
[BUG]: sort_by_key with a key type of long double does not compile

### ISSUE THREAD

**Issue by andrewcorrigan** [NVIDIA/cccl#7865]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

`sort_by_key` with a key type of `long double` does not compile

### How to Reproduce

See godbolt link below.   Compile and run the minimal reproducer below.  I used `host_vector` here, but also originally encountered the failure using `device_vector`

```
#define THRUST_DEVICE_SYSTEM 4
#include <thrust/host_vector.h>
#include <thrust/sort.h>

int main(int argc, char** argv)
{
    thrust::host_vector<int> a(10, 0);
    thrust::host_vector<long double> b(10, 0);

    // works
    thrust::sort_by_key(a.begin(), a.end(), b.begin());

    // doesn't work
    thrust::sort_by_key(b.begin(), b.end(), a.begin());

    return 0;
}
```

### Expected behavior

The code should compile, but instead errors with.  This worked with earlier versions of Thrust.

```
/opt/compiler-explorer/libs/cccl/trunk/thrust/thrust/system/detail/sequential/stable_radix_sort.h:536:3: error: type 'radix_sort_dispatcher<sizeof(KeyType)>' does not provide a call operator
  536 |   radix_sort_dispatcher<sizeof(KeyType)>()(exec, keys1, keys2, vals1, vals2, N);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Reproduction link

https://godbolt.org/z/qb48r3We4

**Comment by bernhardmgruber** [comment]
Switching through various CCCL versions on CE, this used to work in CCCL 2.4 and broke in CCCL 2.5. The change was to choose radix sort over merge sort in the backend.

**Comment by bernhardmgruber** [comment]
The issue was introduced with #1721, when we internally changed from `thrust::detail::is_arithmetic` to `cuda::std::is_arithemtic`, because the former is (wrongly) `false` for `long double` and the latter is `true`.

**Comment by andrewcorrigan** [comment]
thanks for the feedback, fyi, I pushed a fix #7869

**Comment by miscco** [comment]
@davebayer for continuous joy with `long double`

**Comment by davebayer** [comment]
> @davebayer for continuous joy with long double

`long double` never disappoints
