### PR TITLE
Unify assert handling in cccl

### PR DESCRIPTION
**Pull request by miscco**
This works toward unification of assert handling in CCCL

Currently we do not enable assertions even in debug mode, which is ... unfortunate (See #2381)

For libcu++ the user must define `_LIBCUDACXX_ENABLE_DEBUG_MODE` or `_LIBCUDACXX_ENABLE_ASSERTIONS`

None of those macros are user facing or documented anywhere, which makes it really difficult to use. Furthermore, this only works on libcu++ and not Thrust and CUB. However, we want a delightful experience across all our libraries.

To improve the situation and give our users the choice we move the assertion handling into a global CCCL wide facility.

The proposal is to add three distinct, user facing flags:

1. `CCCL_ENABLE_HOST_ASSERTIONS` This enables use of assertions in host code only
2. `CCCL_ENABLE_DEVICE_ASSERTIONS` This enables use of assertions in device code only
3. `CCCL_ENABLE_ASSERTIONS` This enables use of assertions in both host and device code

This allows the user to select what kind of assertions they want to use and whether they want to take the compile-time / performance hit of device assertions.

Finally, we also provide internal facilities to actually use those assertions, namely
1. `_CCCL_VERIFY` This is always on and reserved for  absolutely critical correctness checks. 
2. `_CCCL_ASSERT` This is conditionally on depending on the user provided flag

### CODE REVIEW

File: libcudacxx/include/cuda/std/__cccl/assert.h [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+
+// Automatically enable assertions when the debug mode is enabled manually.
+#ifdef _CCCL_ENABLE_DEBUG_MODE
+#  ifndef _CCCL_ENABLE_ASSERTIONS
+#    define _CCCL_ENABLE_ASSERTIONS
+#  endif // !_CCCL_ENABLE_ASSERTIONS
+#endif // _CCCL_ENABLE_DEBUG_MODE
+
+// Assert that is enabled unconditionally
+#define _CCCL_VERIFY(expression, message)            \
```
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/std/__cccl/assert.h:64]: Is `verify` an existing term of art? If I spotted a `_CCCL_VERIFY(i > 23)` in code I would not immediately know that this is an always-on assertion. But this knowledge could spread over time.

I would have probably called it `_CCCL_ASSERT_ALWAYS`. But there is no need for change.

File: libcudacxx/include/cuda/std/__iterator/wrap_iter.h [hunk 2]
```diff
@@ -59,67 +50,23 @@ class __wrap_iter
...
-    return *this;
-  }
-  _LIBCUDACXX_HIDE_FROM_ABI _CCCL_CONSTEXPR_CXX20 ~__wrap_iter()
-  {
-    if (!__libcpp_is_constant_evaluated())
-    {
-      __get_db()->__erase_i(this);
-    }
-  }
-#endif
```
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/std/__iterator/wrap_iter.h:106]: Question: Why remove all this? And why as part of this PR? It seems unrelated to the assert unification.

File: libcudacxx/test/libcudacxx/CMakeLists.txt [hunk 3]
```diff
@@ -39,6 +39,11 @@ else() # NOT LIBCUDACXX_TEST_WITH_NVRTC
   set(LIBCUDACXX_TEST_COMPILER_FLAGS "-DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE")
 endif()
 
+# enable exceptions and assertions in tests
+string(APPEND LIBCUDACXX_TEST_COMPILER_FLAGS
+       " -DLIBCUDACXX_ENABLE_EXCEPTIONS"
```
Comment (bernhardmgruber) [inline libcudacxx/test/libcudacxx/CMakeLists.txt:44]: Enabling exceptions seems unrelated to this PR? Why was it added? Oversight?

**Review by bernhardmgruber — COMMENTED** [review]
Great work so far, thx! I see no changes to the build system tough. What are users expected to define now to get assertions? `DEBUG`, `_CCCL_ENABLE_DEBUG_MODE`, or `_CCCL_ENABLE_ASSERTIONS`?  And why do we need a distinction between a debug mode and assertions enabled?

File: libcudacxx/include/cuda/std/__cccl/assert.h (hunk 1 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__cccl/assert.h:64]: I have stolen this from MSVC, which has `_STL_VERIFY`

File: libcudacxx/include/cuda/std/__iterator/wrap_iter.h (hunk 2 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__iterator/wrap_iter.h:106]: Thats something i had in that branch lying around. We need to get rid of all the old debug handling

File: libcudacxx/test/libcudacxx/CMakeLists.txt (hunk 3 above)
Comment (miscco) [reply libcudacxx/test/libcudacxx/CMakeLists.txt:44]: I want to enable assertions globally, so we can just as well enable exceptions too

File: libcudacxx/include/cuda/std/__cccl/assert.h (hunk 1 above)
Comment (bernhardmgruber) [reply libcudacxx/include/cuda/std/__cccl/assert.h:64]: Alright, so there is some precedence.

File: libcudacxx/test/libcudacxx/CMakeLists.txt (hunk 3 above)
Comment (bernhardmgruber) [reply libcudacxx/test/libcudacxx/CMakeLists.txt:44]: I can imagine this introducing all kinds of new side effects and possible requiring additional fixes unrelated to assertions. Can we please do it in a separate PR?

**Comment by fbusato** [comment]
would make sense to add an "optimization mode"? namely, mapping assertions to `__builtin_assume` or equivalent? clang already does this underneath

**Comment by miscco** [comment]
> would make sense to add an "optimization mode"? namely, mapping assertions to `__builtin_assume` or equivalent? clang already does this underneath

That is *exceptionally* difficult. On one hand, __builtin_assume is not supported, but more importantly, even clang does not enable it because there are [performance implications ](https://discourse.llvm.org/t/llvm-assume-blocks-optimization/71609)

**Comment by jrhemstad** [comment]
@miscco can you update the PR description with a summary of the approach we're taking to unify things and what the default behavior will be?

File: libcudacxx/include/cuda/std/__cccl/assert.h [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+#  endif // !CCCL_ENABLE_HOST_ASSERTIONS
+#endif // !__CUDA_ARCH__
+
+//! _CCCL_VERIFY is an unconditionally enabled assertion that is reserved for the most important checks
+//! Some compilers warn about `is_constant_evaluated()` in a non constexpr function, so silence that right away
+#if defined(_CCCL_COMPILER_ICC)
+#  define _CCCL_VERIFY(expression, message) \
+    _CCCL_DIAG_PUSH _CCCL_DIAG_SUPPRESS_ICC(4190) _CCCL_ASSERT_IMPL(expression, message) _CCCL_DIAG_POP
+#else // ^^^ _CCCL_COMPILER_ICC ^^^ / vvv !_CCCL_COMPILER_ICC vvv
+#  define _CCCL_VERIFY(expression, message) _CCCL_ASSERT_IMPL(expression, message)
```
Comment (dkolsen-pgi) [inline libcudacxx/include/cuda/std/__cccl/assert.h:114]: If `__CUDA_ARCH__` is defined but `CCCL_ENABLE_DEVICE_ASSERTIONS` is not defined, then `_CCCL_ASSERT_IMPL` will be defined as empty, so `_CCCL_VERIFY(expression, message)` will expand to `(expression, message)`.  That will compile and behave correctly, but it's not what you want.

If neither `__CUDA_ARCH__` nor `CCCL_ENABLE_HOST_ASSERTIONS` are defined, then `_CCCL_ASSERT_IMPL` is not defined at all, so `_CCCL_VERIFY(expression, message)` will expand to `_CCCL_ASSERT_IMPL(expression, message)`, which is a compilation error.

Since `_CCCL_VERIFY` is always defined, `_CCCL_ASSERT_IMPL` must always be defined.  If it can't be defined as something meaningful, then it should be `#define _CCCL_ASSERT_IMPL(expression, message) ((void)0)`

File: libcudacxx/include/cuda/std/__cccl/assert.h [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+
+//! Ensure that we switch on device assertions when all assertions are enabled
+#ifndef CCCL_ENABLE_DEVICE_ASSERTIONS
+#  ifdef CCCL_ENABLE_ASSERTIONS
+#    define CCCL_ENABLE_DEVICE_ASSERTIONS
+#  endif // CCCL_ENABLE_ASSERTIONS
+#endif // !CCCL_ENABLE_DEVICE_ASSERTIONS
+
+//! Use internal nvcc implementation on device or the host library for clang-cuda
+#ifdef __CUDA_ARCH__
```
Comment (dkolsen-pgi) [inline libcudacxx/include/cuda/std/__cccl/assert.h:55]: This file, `cuda/std/__cccl/assert.h`, ignores NVC++ entirely, and won't work correctly for `nvc++ -stdpar=gpu`.  The file assumes that host and device code are compiled separately, and that `__CUDA_ARCH__` is defined when compiling device code and `__CUDA_ARCH__` is not defined when compiling host code.

`nvc++ -stdpar=gpu` compiles both host and device code in a single pass and does not define `__CUDA_ARCH__`.  It is probably necessary to give NVC++ special handling, separate from all the logic that is here.  `_CCCL_ASSERT_IMPL` would be defined as something that works in both host and device code with NVC++.  (`__assert_fail` might work in both host and device code with NVC++, but that should be verified.)

File: libcudacxx/include/cuda/std/__cccl/assert.h [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+#ifndef __CUDA_ARCH__
+#  ifdef CCCL_ENABLE_HOST_ASSERTIONS
+#    if __has_include(<yvals_core.h>) // MSVC uses _STL_VERIFY from <yvals_core.h>
+#      include <yvals_core.h>
+#      define _CCCL_ASSERT_IMPL(expression, message) _STL_VERIFY(expression, message)
+#    elif __has_include(<__assert>) // libc++ uses _LIBCPP_ASSERT from <__assert>
+#      include <__assert>
+#      define _CCCL_ASSERT_IMPL(expression, message) _LIBCPP_ASSERT(expression, message)
+#    else // libstdc++ uses __glibcxx_assert from <bits/c++config.h
+#      include <bits/c++config.h>
```
Comment (dkolsen-pgi) [inline libcudacxx/include/cuda/std/__cccl/assert.h:94]: If none of `<yvals_core.h>`, `<__assert>`, or `<bits/c++config.h>` are available, then compilation will fail with an error about `<bits/c++config.h>` not being found.

If you want compilation to fail if CCCL is used in an unsupported or unexpected environment, then it should fail with an `#error` that explains why.

If CCCL assertions should gracefully handle unexpected environment, presumably by disabling assertions, then there should be a check for `<bits/c++config.h>` and `_CCCL_ASSERT_IMPL` should be a no-op if that check fails.

**Review by dkolsen-pgi — CHANGES_REQUESTED** [review]
The big problem here is that `__cccl/assert.h` doesn't handle `nvc++ -stdpar`.

File: libcudacxx/include/cuda/std/__cccl/assert.h (hunk 5 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__cccl/assert.h:55]: I reworked the approach to use the host standard library on host and only use the special fallback for nvcc on device.

The `_CCCL_ASSERT_IMPL` now forwards to `_NV_IF_TARGET`

File: libcudacxx/include/cuda/std/__cccl/assert.h (hunk 6 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__cccl/assert.h:94]: Thanks a lot, I have added an error message for that

**Review by dkolsen-pgi — APPROVED** [review]
I only looked at `cuda/std/__cccl/assert.h`.  It looks fine to me.  Thank you for using `NV_IF_TARGET` only for NVC++.  I was going to suggest that.

**Comment by jrhemstad** [comment]
> CCCL_ENABLE_HOST_ASSERTIONS This enables use of assertions in host code only
> CCCL_ENABLE_DEVICE_ASSERTIONS This enables use of assertions in device code only
> CCCL_ENABLE_ASSERTIONS This enables use of assertions in both host and device code

What is the default state for these flags and how does it interact with `NDEBUG`?

**Comment by miscco** [comment]
> > CCCL_ENABLE_HOST_ASSERTIONS This enables use of assertions in host code only
> > CCCL_ENABLE_DEVICE_ASSERTIONS This enables use of assertions in device code only
> > CCCL_ENABLE_ASSERTIONS This enables use of assertions in both host and device code
> 
> What is the default state for these flags and how does it interact with `NDEBUG`?

I need to write some documentation dont I

The default is that those flags are not defined.

We only define them when the user defines `DEBUG` or `_DEBUG` and when the user defines `CCCL_ENABLE_ASSERTIONS `

**Review by ericniebler — APPROVED** [review]
looks good. a big improvement.

**Comment by SoapGentoo** [comment]
@miscco is `CCCL_ENABLE_ASSERTIONS` user-facing and guaranteed to be stable? I'd like to put this in Meson as the nvcc/cuda equivalent of libstdc++'s `_GLIBCXX_ASSERTIONS`, since these checks are invaluable in CI and general debugging.

**Comment by miscco** [comment]
> @miscco is `CCCL_ENABLE_ASSERTIONS` user-facing and guaranteed to be stable? I'd like to put this in Meson as the nvcc/cuda equivalent of libstdc++'s `_GLIBCXX_ASSERTIONS`, since these checks are invaluable in CI and general debugging.

yes this is a user facing machinery that we consider as stable per our usual stability guidelines. 

I would like to note that `CCCL_ENABLE_ASSERTIONS` enables assertions on both host *and* device, which might not be desired, so also adding support for `CCCL_ENABLE_HOST_ASSERTIONS` and `CCCL_ENABLE_DEVICE_ASSERTIONS` would be advisable
