### ISSUE TITLE
pointer_traits specialization for device_ptr uses struct rebind, breaking allocator_traits::void_pointer

### ISSUE THREAD

**Issue by bdice** [NVIDIA/cccl#8485]
## Summary

PR #7439 (commit 577b7d90ef51) introduced explicit `cuda::std::pointer_traits` specializations for thrust smart pointers. The specialization for `thrust::device_ptr<T>` in `thrust/device_ptr.h` defines `rebind` as a nested struct:

```cpp
template <typename U>
struct rebind {
  using other = typename thrust::detail::rebind_pointer<pointer, U>::type;
};
```

However, `cuda::std::allocator_traits` computes `void_pointer` via:

```cpp
using type = typename pointer_traits<_Ptr>::template rebind<void>;
```

This expects `rebind` to be an **alias template** (as in the primary `__pointer_traits_impl`), not a nested struct. With the struct form, `pointer_traits<device_ptr<char>>::rebind<void>` resolves to the **struct type itself** rather than `device_ptr<void>`.

This breaks any allocator whose `pointer` type is `thrust::device_ptr<T>` — notably RMM's `thrust_allocator<char>`, which is used pervasively across RAPIDS.

## Affected Version

main branch, post-v3.3.0. Introduced by #7439 (commit 577b7d90ef51). Confirmed via `git bisect`.

## Impact

All three RAPIDS third-party build jobs fail in nightly CI ([run 24491505141](https://github.com/NVIDIA/cccl/actions/runs/24491505141)):

| Job | Failing Library | Failing Source |
|-----|----------------|----------------|
| `rmm ucxx raft cugraph` | cugraph | `random_walks_mg_v64_e64.cu` |
| `rmm ucxx raft cuvs cuml` | cuvs | `ivf_pq_build_extend_inst_data_h_index_i64.cu` |
| `rmm kvikio cudf cudf_kafka` | cudf | `sha1_hash.cu` |

All failures trace through `thrust::detail::get_temporary_buffer` → `execute_with_allocator` → `allocator_traits::void_pointer` → `pointer_traits::rebind<void>`.

## Error Messages

```
execute_with_allocator.h(42): error: no suitable user-defined conversion from
  "cuda::std::allocator_traits<...>::pointer" (aka "thrust::device_ptr<char>")
  to "void_pointer" (aka "cuda::std::pointer_traits<thrust::device_ptr<char>, void>::rebind<void>") exists
    void_pointer ptr = alloc_traits::allocate(system.get_allocator(), num_elements);

pointer_traits.h(161): error: class
  "cuda::std::pointer_traits<thrust::device_ptr<T>, void>::rebind<void> [with T=char]"
  has no member "get"
      return ptr.get();
```

## Minimal Reproducer

Failing with `main`: https://godbolt.org/z/aeredxvTj
Passing with `v3.3.2`: https://godbolt.org/z/Gz8Khn8W5

```cuda
// Build: nvcc -std=c++17 -I<cccl>/thrust -I<cccl>/libcudacxx/include -I<cccl>/cub repro.cu

#include <thrust/device_ptr.h>
#include <cuda/std/__memory/allocator_traits.h>
#include <cuda/std/__memory/pointer_traits.h>

struct device_char_allocator {
  using value_type = char;
  using pointer    = thrust::device_ptr<char>;
  pointer allocate(std::size_t n);
  void deallocate(pointer p, std::size_t);
};

using alloc_traits = cuda::std::allocator_traits<device_char_allocator>;
using void_pointer = alloc_traits::void_pointer;

static_assert(
  cuda::std::is_same_v<void_pointer, thrust::device_ptr<void>>,
  "void_pointer should be device_ptr<void>");
```

## Root Cause

The `device_ptr<T>` specialization of `pointer_traits` (`thrust/device_ptr.h:233`) and the generic thrust pointer specialization (`thrust/detail/pointer.h`) both define `rebind` as a nested struct with `::other`. The primary `__pointer_traits_impl` (`libcudacxx/include/cuda/std/__memory/pointer_traits.h:122`) defines it as an alias template. `allocator_traits` uses the alias template convention (`rebind<U>` yields the type directly). Since the explicit specializations win, the struct form is selected, and the type algebra breaks.

## Suggested Fix

Change `rebind` from a nested struct to an alias template in the affected specializations. For example, in `thrust/device_ptr.h`:

```cpp
// Before (broken):
template <typename U>
struct rebind {
  using other = typename thrust::detail::rebind_pointer<pointer, U>::type;
};

// After (fixed):
template <typename U>
using rebind = typename thrust::detail::rebind_pointer<pointer, U>::type;
```

The same change is needed in the generic specialization in `thrust/detail/pointer.h`.
