### ISSUE TITLE
[BUG]: CUDA 13, nvcc compilation error when including `<thrust/execution_policy.h>` with THRUST_DEVICE_SYSTEM_OMP in cpp file

### ISSUE THREAD

**Issue by fkallen** [NVIDIA/cccl#5747]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

The following fails to compile with CUDA 13.0 nvcc in a .cpp file

```
//nvcc -c file.cpp -o file.o
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_OMP
#include <thrust/execution_policy.h>
```

```
In file included from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__ptx/instructions/bfind.h:26,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/std/__bit/integral.h:24,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__cmath/ilog.h:24,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/cmath:25,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/detail/alignment.h:32,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/detail/allocator_aware_execution_policy.h:28,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/detail/seq.h:28,
                 from /usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/thrust/execution_policy.h:34,
                 from file.cpp:3:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__ptx/ptx_helper_functions.h: In function ‘uint32_t cuda::ptx::__4::__as_ptr_smem(const void*)’:
/usr/local/cuda-13.0/targets/x86_64-linux/include/cccl/cuda/__ptx/ptx_helper_functions.h:42:44: error: ‘__cvta_generic_to_shared’ was not declared in this scope
   42 |   return static_cast<_CUDA_VSTD::uint32_t>(__cvta_generic_to_shared(__ptr));

```

### How to Reproduce

```
//nvcc -c file.cpp -o file.o
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_OMP
#include <thrust/execution_policy.h>
```

### Expected behavior

Compiles without error.

**Comment by miscco** [comment]
Thanks a lot for the bug report. 

It seems we have missed to guard some includes of ptx functionality for when we are compiling in cuda mode.

I have opened a PR to fix this

**Comment by alliepiper** [comment]
From the coverage side, we do test for this -- but using the host compiler directly, not nvcc. I'll patch this gap.

**Comment by alliepiper** [comment]
Reopened this to track the CI gap fix.
