### ISSUE TITLE
[BUG]: Clang-tidy bugprone-move-forwarding-reference error in cuda/std/__algorithm/set_difference.h

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [NVIDIA/cccl#10934]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

libcu++

### Describe the bug

```
/home/coder/cccl/libcudacxx/include/cuda/std/__algorithm/set_difference.h:62:5: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
   62 |     ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
      |     ^
/home/coder/cccl/libcudacxx/include/cuda/std/__algorithm/set_difference.h:62:34: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
   62 |     ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
      |                                  ^
/home/coder/cccl/libcudacxx/include/cuda/std/__algorithm/set_difference.h:62:62: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
   62 |     ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
      |                                                              ^
3 warnings treated as errors
```

Encountered in https://github.com/NVIDIA/cccl/pull/10898#issuecomment-5362008101

<strike>
**Suggested fix**: Include `<cuda/std/__utility/forward.h>` in `set_difference.h` and replace the three moves at line 62 with `cuda::std::forward<_InIter1>(__first1)`, `cuda::std::forward<_Sent1>(__last1)`, and `cuda::std::forward<_OutIter>(__result)`.
</strike>

### How to Reproduce

```cpp
// Reproducer for clang-tidy bugprone-move-forwarding-reference in
// cuda/std/__algorithm/set_difference.h.

#include <cuda/std/__algorithm/set_difference.h>

int main()
{
  int lhs[] = {1, 2, 3};
  int rhs[] = {2};
  int out[] = {0, 0, 0};

  auto* const end = cuda::std::set_difference(lhs, lhs + 3, rhs, rhs + 1, out);

  return (end == out + 2) ? 0 : 1;
}
```

Compile in cuda-12.9-llvm21 devcontainer using

```
clang-tidy-21 cccl_set_difference_tidy_repro.cpp \
    --checks='-*,bugprone-move-forwarding-reference'  \
    --warnings-as-errors='bugprone-move-forwarding-reference' \
    --header-filter='.*libcudacxx/include/cuda/std/__algorithm/set_difference\.h' \
    --system-headers -- -std=c++20 -I "$PWD/libcudacxx/include"
```

### Expected behavior

No clang-tidy errors
