### PR TITLE
Use by value semantics in __set_difference helper in  set_difference.h

### LINKED ISSUE #10934: [BUG]: Clang-tidy bugprone-move-forwarding-reference error in cuda/std/__algorithm/set_difference.h
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

libcu++

### Describe the bug

```
/home/coder/cccl/libcudacxx/include/cuda/std/__algorithm/set_difference.h:62:5: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
   62 |     ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
      |     ^
/home/coder/cccl/libcudacxx/include/cuda/std/__algorithm/set_difference.h:62:34: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
   62 |     ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
      |                                  ^
/home/coder/cccl/libcudacxx/include/cuda/std/__algorithm/set_difference.h:62:62: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
   62 |     ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
      |                                                              ^
3 warnings treated as errors
```

Encountered in https://github.com/NVIDIA/cccl/pull/10898#issuecomment-5362008101

<strike>
**Suggested fix**: Include `<cuda/std/__utility/forward.h>` in `set_difference.h` and replace the three moves at line 62 with `cuda::std::forward<_InIter1>(__first1)`, `cuda::std::forward<_Sent1>(__last1)`, and `cuda::std::forward<_OutIter>(__result)`.
</strike>

### How to Reproduce

```cpp
// Reproducer for clang-tidy bugprone-move-forwarding-reference in
// cuda/std/__algorithm/set_difference.h.

#include <cuda/std/__algorithm/set_difference.h>

int main()
{
  int lhs[] = {1, 2, 3};
  int rhs[] = {2};
  int out[] = {0, 0, 0};

  auto* const end = cuda::std::set_difference(lhs, lhs + 3, rhs, rhs + 1, out);

  return (end == out + 2) ? 0 : 1;
}
```

Compile in cuda-12.9-llvm21 devcontainer using

```
clang-tidy-21 cccl_set_difference_tidy_repro.cpp \
    --checks='-*,bugprone-move-forwarding-reference'  \
    --warnings-as-errors='bugprone-move-forwarding-reference' \
    --header-filter='.*libcudacxx/include/cuda/std/__algorithm/set_difference\.h' \
    --system-headers -- -std=c++20 -I "$PWD/libcudacxx/include"
```

### Expected behavior

No clang-tidy errors

### Reproduction link

_No response_

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
The warning was a false positive per @miscco (https://github.com/NVIDIA/cccl/pull/10938#pullrequestreview-4995146135)

## Description

closes #10934

**Update**: the controversial NOLINT addition is removed. `__set_difference` now takes iterators by value.

## Checklist

- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

File: libcudacxx/include/cuda/std/__algorithm/set_difference.h [hunk 1]
```diff
@@ -59,7 +59,9 @@ _CCCL_API constexpr pair<remove_cvref_t<_InIter1>, remove_cvref_t<_OutIter>> __s
     }
   }
   return ::cuda::std::__copy<_AlgPolicy>(
-    ::cuda::std::move(__first1), ::cuda::std::move(__last1), ::cuda::std::move(__result));
+    ::cuda::std::move(__first1), // NOLINT(bugprone-move-forwarding-reference)
+    ::cuda::std::move(__last1), // NOLINT(bugprone-move-forwarding-reference)
+    ::cuda::std::move(__result)); // NOLINT(bugprone-move-forwarding-reference)
```
Comment (Jacobfaib) [inline libcudacxx/include/cuda/std/__algorithm/set_difference.h]: We should use `forward` instead, this will silence `clang-tidy` as well (and is  the right solution anyways).

Comment (oleksandr-pavlyk) [reply libcudacxx/include/cuda/std/__algorithm/set_difference.h]: The change to use forward was #10938, but @miscco insists `move` rather than `forward` is the correct semantics here (https://github.com/NVIDIA/cccl/pull/10938#pullrequestreview-4995146135).

Comment (Jacobfaib) [reply libcudacxx/include/cuda/std/__algorithm/set_difference.h]: @miscco why move? The iterators are taken as `&&`...

Comment (griwes) [reply libcudacxx/include/cuda/std/__algorithm/set_difference.h]: Yeah, this makes no sense to me tbqh. I cannot see a reason that'd make this be an actual false positive - the linter appears entirely correct here. We need to either (1) forward here, or, better, (2) just accept the iterators as values, not as forwarding references. That last part is what also makes no sense to me - why are we accepting them by forwarding references and not values? If they were just plain values, all of this would be much more obvious...

**Review by griwes — CHANGES_REQUESTED** [review]

**Comment by miscco** [comment]
Yeah we should probably just move in the top level function and accept by value, which is much more consistent with what we do everywhere else

**Review by Jacobfaib — APPROVED** [review]

**Review by miscco — APPROVED** [review]

**Review by griwes — APPROVED** [review]

**Review by bernhardmgruber — APPROVED** [review]
