### ISSUE TITLE
[BUG]: CTK 12.5 breaks `unique_by_key_copy` with keys that don't have an equality operator.

### ISSUE THREAD

**Issue by trivialfis** [NVIDIA/cccl#1956]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

The following code compiles with CTK12.4 but not with 12.5. We rely on using a transform iterator with outputs that cannot be directly compared and use the key comparison function argument for the job.
``` cuda
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
#include <thrust/unique.h>

struct Entry {
  std::int32_t a{0};
  float b{0};
};

int main() {
  using Key = thrust::pair<std::int32_t, Entry>;

  thrust::device_vector<Key> keys(10);
  thrust::device_vector<Entry> data(10);

  thrust::device_vector<Key> unique_keys(10);
  thrust::device_vector<Entry> unique_data(10);

  thrust::unique_by_key_copy(
      thrust::device, keys.cbegin(), keys.cend(), data.begin(),
      unique_keys.begin(), unique_data.begin(),
      [] __host__ __device__(Key const &lhs, Key const &rhs) {
        return lhs.first == rhs.first;
      });
  return 0;
}
```

An excerpt of the compilation error:
```
/usr/local/cuda-12.5/targets/x86_64-linux/include/cuda/std/detail/libcxx/include/__utility/pair.h(577): error: no operator "==" matches these operands
            operand types are: const Entry == const Entry
    return __x.first == __y.first && __x.second == __y.second;
                                                ^
/usr/local/cuda-12.5/targets/x86_64-linux/include/cuda/std/detail/libcxx/include/__iterator/wrap_iter.h(212): note #3327-D: candidate function template "cuda::std::__4::operator==(const cuda::std::__4::__wrap_iter<_Iter1> &, const cuda::std::__4::__wrap_iter<_Iter2> &) noexcept" failed deduction
  operator==(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter2>& __y) noexcept
  ^
/usr/local/cuda-12.5/targets/x86_64-linux/include/cuda/std/detail/libcxx/include/__iterator/wrap_iter.h(205): note #3327-D: candidate function template "cuda::std::__4::operator==(const cuda::std::__4::__wrap_iter<_Iter1> &, const cuda::std::__4::__wrap_iter<_Iter1> &) noexcept" failed deduction
  operator==(const __wrap_iter<_Iter1>& __x, const __wrap_iter<_Iter1>& __y) noexcept
  ^
```

### How to Reproduce

See the above code snippet.

### Expected behavior

It should compile successfully and use the key comparison operator.

### Operating System

Ubuntu 22.04

### nvidia-smi output

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:01:00.0  On |                  N/A |
|  0%   43C    P8             15W /  285W |     365MiB /  16376MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4070 ...    Off |   00000000:03:00.0 Off |                  N/A |
|  0%   45C    P8              8W /  285W |      10MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      5538      G   /usr/bin/gnome-shell                          356MiB |
|    1   N/A  N/A      5538      G   /usr/bin/gnome-shell                            3MiB |
+-----------------------------------------------------------------------------------------+
```

### NVCC version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0

**Comment by bernhardmgruber** [comment]
Thanks for reporting this issue! The issue slipped in during a refactoring in #1245. I prepared a fix: #1957.
